EmlakPlus.WEBUI/Controllers/WhoWeAreController.cs
using AutoMapper;
using EmlakPlus.BLL.Abstract;
using EmlakPlus.BLL.DTOs.SliderDTO;
using EmlakPlus.BLL;
using EmlakPlus.Entity;
using EmlakPlus.WEBUI.Models;
using Microsoft.AspNetCore.Mvc;
using EmlakPlus.BLL.DTOs.WhoWeAreDTO;

namespace EmlakPlus.WEBUI.Controllers
{
    public class WhoWeAreController : Controller
    {
        private readonly IWhoWeAreService _whoWeAreService;
        private readonly IMapper _mapper;

        public WhoWeAreController(IWhoWeAreService whoWeAreService, IMapper mapper)
        {
            _whoWeAreService = whoWeAreService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var whoWeAre = _whoWeAreService.GetOne();
            return View(_mapper.Map<ResultWhoWeAreDTO>(whoWeAre));
        }

        public IActionResult Edit(int id)
        {
            var whoWeAre = _whoWeAreService.GetOne();
            return View(_mapper.Map<UpdateWhoWeAreDTO>(whoWeAre));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(UpdateWhoWeAreDTO dto, IFormFile file)
        {
            ModelState.Remove("Image");
            if (ModelState.IsValid)
            {
                var whoWeAre = _whoWeAreService.GetOne();

                if (whoWeAre == null)
                {
                    ErrorViewModel error = new ErrorViewModel()
                    {
                        Code = 404,
                        Title = "Slider Bulunamadı",
                        Description = "Lütfen seçtiğiniz yapıyı tekrar kontrol ediniz.",
                        ReturnUrl = "/whoWeAre/Index",
                        Css = "text-danger"
                    };
                    return View("Error", error);
                }

                if (file != null)
                {
                    if (whoWeAre.Image != null)
                    {
                        ImageMethods.DeleteImage(whoWeAre.Image);
                    }

                    dto.Image = await ImageMethods.UploadImage(file);
                }

                _whoWeAreService.Update(_mapper.Map<WhoWeAre>(dto));
                return RedirectToAction("Index");
            }

            return View(dto);
        }

    }
}

EmlakPlus.WEBUI/Views/WhoWeAre/Edit.cshtml
@model UpdateWhoWeAreDTO
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <!-- general form elements -->
        <div class="card card-primary">
            <!-- form start -->
            <form asp-controller="WhoWeAre" asp-action="Edit" method="post" enctype="multipart/form-data">
                <input type="hidden" name="Id" value="@Model.Id" />
                <input type="hidden" name="Image" id="Image" value="@Model.Image" />
                <div class="card-body">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Title"></label>
                                <input asp-for="Title" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Description"></label>
                                <input asp-for="Description" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>

                            @for (int i = 0; i < Model.Employments.Count; i++)
                            {
                                <div class="form-check mb-2">
                                    <input class="form-check-input" type="checkbox" name="Employments[@i].Status" value="true" @(Model.Employments[i].Status ? "checked" : "")>
                                    <input asp-for="@Model.Employments[i].Title" class="form-control" />
                                </div>
                            }

                           
                            <div class="card-footer text-center">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Güncelle</button>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="form-group">
                                <label asp-for="Image"></label><br />
                                <img id="previewImage" src="~/img/@Model.Image" class="card-img-top" alt="..." style="max-width:100%">
                            </div>
                            <div class="form-group">
                                <input type="file" id="imageInput" name="file" value="@Model.Image" accept="image/*" onchange="updateCard()" />
                               
                            </div>
                        </div>
                        <!-- /.card-body -->
                    </div>
            </form>
        </div>
        <!-- /.card -->

    </div>
</div>

<script>
    function updateCard() {
        var input = document.getElementById('imageInput');
        var preview = document.getElementById('previewImage');
        var file = input.files[0];
        var reader = new FileReader();
        reader.onloadend = function () {
            preview.src = reader.result;
        }
        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
   
</script>

EmlakPlus.WEBUI/Views/WhoWeAre/Index.cshtml
@model ResultWhoWeAreDTO
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Biz Kimiz</h3>
            </div>
            <!-- /.card-header -->
            <div class="card-body table-responsive p-0">
                <table class="table table-hover text-nowrap">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Resim</th>
                            <th>Başlık</th>
                            <th>Açıklama</th>
                            <th>Güncelle</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.Id</td>
                            <td><img class="img-fluid" src="~/img/@Model.Image" alt="Icon"></td>
                            <td>@Model.Title</td>
                            <td style="text-wrap: wrap;">@Model.Description</td>
                           
                            <td><a href="/WhoWeAre/Edit?id=@Model.Id" class="btn btn-outline-warning">Güncelle</a></td>
                        </tr>
                    </tbody>
                </table>

            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->
    </div>
</div>